global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: your_mail_address
  smtp_auth_username: your_mail_address
  smtp_auth_password: your_auth_passwd
  smtp_auth_identity: your_mail_address

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: your_mail_address
