global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: ${YOUR MAIL ADRESSES}
  smtp_auth_username: ${YOUR MAIL ADRESSES}
  smtp_auth_password: ${your auth passwd}
  smtp_auth_identity: ${YOUR MAIL ADRESSES}

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: '${YOUR MAIL ADRESSES}'
