global:
  scrape_interval: 10s
  evaluation_interval: 10s

    #rule_files:
    #- rules.yml
# uncomment above to enable the defined rule in rule.yml 
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['172.29.138.153:9093']
        
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.29.138.153:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['172.29.138.153:9100']
  
  - job_name: 'loki'
    static_configs: 
      - targets: ['172.29.138.153:3100']
